Update 12 .yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,10 +20,10 @@ jobs:
         with:
           token: ${{ secrets.ACCESS_TOKEN }}
 
-      - name: Set up Python 3.12.7
+      - name: Set up Python 3.11
         uses: actions/setup-python@v4
         with:
-          python-version: "3.12.7"
+          python-version: "3.11"
 
       - name: Check Env
         run: |
@@ -32,14 +32,21 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install mlflow
+          pip install mlflow==2.17.0 pandas==2.2.3 numpy==2.1.1 scikit-learn==1.5.2 scipy==1.14.1 cloudpickle==3.1.0 psutil==6.1.0 git-lfs
+
+      - name: Clean mlruns
+        run: |
+          rm -rf mlruns/ || echo "No mlruns folder to clean"
 
       - name: Run mlflow project
         run: |
+          export MLFLOW_TRACKING_URI=file://$(pwd)/mlruns
+          ls -la MLproject/ || echo "MLproject folder not found"
+          ls -la MLproject/train_pca.csv || echo "train_pca.csv not found"
           mlflow run ./MLproject --env-manager=local -P csv_url=$CSV_URL
 
-      - name: Set up Git LFS
-        run: |
+      -  name: Set up Git LFS
+         run: |
            git config --global user.name ${{ secrets.username }}
            git config --global user.email ${{ secrets.email }}
            git lfs install
@@ -53,6 +60,6 @@ jobs:
           git config --global user.name ${{ secrets.username }}
           git config --global user.email ${{ secrets.email }}
           git remote set-url origin https://${{ secrets.username }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
-          git add mlruns/
-          git commit -m "Save mlruns from CI run"
+          git add -f mlruns/
+          git commit -m "Save mlruns from CI run" || true
           git push origin main
